// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"bytes"
	"encoding/json"
	"text/template"

	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/properties/{id}/favorites": {
            "post": {
                "description": "Toggle favorite for the authenticated user on a property",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties",
                    "favorites"
                ],
                "summary": "Toggle property favorite",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Property ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/property_types": {
            "get": {
                "description": "List property types",
                "produces": ["application/json"],
                "tags": ["property_types"],
                "summary": "List property types",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query",
                        "required": false
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query",
                        "required": false
                    }
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "object", "additionalProperties": true}},
                    "400": {"description": "Bad Request", "schema": {"type": "object", "additionalProperties": {"type": "string"}}}
                }
            },
            "post": {
                "description": "Create a new property type",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["property_types"],
                "summary": "Create property type",
                "parameters": [{"in": "body", "name": "body", "required": true, "schema": {"type": "object"}}],
                "responses": {"201": {"description": "Created", "schema": {"type": "object"}}, "400": {"description": "Bad Request"}}
            }
        },
        "/property_types/{id}": {
            "get": {
                "description": "Get property type by id",
                "produces": ["application/json"],
                "tags": ["property_types"],
                "summary": "Get property type",
                "parameters": [{"type": "integer", "description": "Property Type ID", "name": "id", "in": "path", "required": true}],
                "responses": {"200": {"description": "OK", "schema": {"type": "object"}}, "400": {"description": "Bad Request"}}
            },
            "put": {
                "description": "Update property type",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["property_types"],
                "summary": "Update property type",
                "parameters": [
                    {"type": "integer", "description": "Property Type ID", "name": "id", "in": "path", "required": true},
                    {"in": "body", "name": "body", "required": true, "schema": {"type": "object"}}
                ],
                "responses": {"204": {"description": "No Content"}, "400": {"description": "Bad Request"}}
            },
            "delete": {
                "description": "Delete property type",
                "produces": ["application/json"],
                "tags": ["property_types"],
                "summary": "Delete property type",
                "parameters": [{"type": "integer", "description": "Property Type ID", "name": "id", "in": "path", "required": true}],
                "responses": {"200": {"description": "OK", "schema": {"type": "object"}}, "400": {"description": "Bad Request"}}
            }
        },
        "/users/{id}/active": {
            "post": {
                "description": "Toggle user's active state (owner or admin)",
                "tags": [
                    "users"
                ],
                "summary": "Toggle active state",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/favorites": {
            "get": {
                "description": "List favorites for given user id (owner only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users",
                    "favorites"
                ],
                "summary": "List user's favorites",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/profile": {
            "put": {
                "description": "Update profile for a user (owner or admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Profile",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.UpdateProfileRequest": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Estate Agency API",
	Description:      "API for Estate Agency service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

// ReadDoc renders and returns the swagger document as JSON string.
// The generator usually emits a ReadDoc helper; some generator/runtime
// version mismatches may omit it. We render the template here to ensure
// the main application can call docs.ReadDoc() to obtain the JSON.
func ReadDoc() string {
	// helper functions used by the template generated by swag
	funcs := template.FuncMap{
		"marshal": func(v interface{}) string {
			b, _ := json.Marshal(v)
			return string(b)
		},
		"escape": func(s string) string {
			b, _ := json.Marshal(s)
			if len(b) >= 2 {
				// strip surrounding quotes
				return string(b[1 : len(b)-1])
			}
			return s
		},
	}

	tmpl, err := template.New("swagger").Funcs(funcs).Parse(docTemplate)
	if err != nil {
		// fallback: return raw template if parsing fails
		return docTemplate
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, SwaggerInfo); err != nil {
		return docTemplate
	}
	return buf.String()
}
